# Generated by Django 3.0.4 on 2020-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='PaperDifficulty',
        ),
        migrations.AddField(
            model_name='review',
            name='contentcoveredduringlectures',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='teachingmethod',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
