# Generated by Django 3.0.4 on 2020-03-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200327_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='PaperDifficulty',
            new_name='Paper_Difficulty_out_of_10',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='contentcoveredduringlectures',
            new_name='content_covered_during_lectures_out_of_10',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='teachingmethod',
            new_name='teaching_method_out_of_10',
        ),
    ]
